In [1]:
import pandas as pd

In [2]:
dfI=pd.read_csv('DataToClean/int.csv')
dfD=pd.read_csv('DataToClean/dom.csv')
df=pd.concat([dfI,dfD],axis=0,ignore_index=True)
df

,Unnamed: 0,MatchID,Stadium,Team,Date,Player,Runs,FBalls,Dismissals,StrikeRate,...,Balls Bowled,Wickets,Catches,Stumpings,RunOuts,Extras,Fours,Sixes,Overs,Maidens
0,0,3817.0,"Brisbane Cricket Ground, Woolloongabba",Pakistan,2017-01-13,DA Warner,3,19,1,15.789474,...,0,0,0,0,0,0,1,0,0,0
1,1,3817.0,"Brisbane Cricket Ground, Woolloongabba",Pakistan,2017-01-13,TM Head,15,39,1,38.461538,...,0,0,0,0,0,0,6,0,0,0
2,2,3817.0,"Brisbane Cricket Ground, Woolloongabba",Pakistan,2017-01-13,SPD Smith,0,1,1,0.000000,...,0,0,0,0,0,0,0,0,0,0
3,3,3817.0,"Brisbane Cricket Ground, Woolloongabba",Pakistan,2017-01-13,CA Lynn,6,14,1,42.857143,...,0,0,0,0,0,0,1,1,0,0
4,4,3817.0,"Brisbane Cricket Ground, Woolloongabba",Pakistan,2017-01-13,MR Marsh,4,17,1,23.529412,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160432,54294,NaN,"Guyana National Stadium, Providence",Jamaica,2022-06-25,S Carrington,0,0,0,0.000000,...,0,0,2,0,0,0,0,0,0,0
160433,54295,NaN,"Guyana National Stadium, Providence",Jamaica,2022-06-25,HK Matthews,0,0,0,0.000000,...,0,0,0,0,1,0,0,0,0,0
160434,54296,NaN,"Guyana National Stadium, Providence",Jamaica,2022-06-25,Kycia A Knight,0,0,0,0.000000,...,0,0,0,0,1,0,0,0,0,0
160435,54297,NaN,"Guyana National Stadium, Providence",Jamaica,2022-06-25,Kyshona A Knight,0,0,0,0.000000,...,0,0,0,0,1,0,0,0,0,0
160436,54298,NaN,"Guyana National Stadium, Providence",Jamaica,2022-06-25,AA Alleyne,0,0,0,0.000000,...,0,0,0,0,1,0,0,0,0,0

In [3]:
#df.set_index('Player', inplace=True)
df.drop('Unnamed: 0', axis=1, inplace=True)

In [4]:
df.columns

Index(['MatchID', 'Stadium', 'Team', 'Date', 'Player', 'Runs', 'FBalls',
       'Dismissals', 'StrikeRate', 'Economy', 'Runs Conceded', 'Balls Bowled',
       'Wickets', 'Catches', 'Stumpings', 'RunOuts', 'Extras', 'Fours',
       'Sixes', 'Overs', 'Maidens'],
      dtype='object')

In [5]:
df.to_csv('WholeData.csv')